# Generated by Django 3.0.7 on 2020-06-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('text', models.TextField(verbose_name='Текст')),
                ('photo', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('pub_date', models.DateField(verbose_name='Дата публикации')),
                ('sep_page', models.BooleanField(verbose_name='Нужна ли отдельная ссылка')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Urgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Срочно')),
                ('link', models.CharField(default=None, max_length=20, verbose_name='Ссылка')),
            ],
        ),
    ]
