# Generated by Django 3.0.7 on 2020-06-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgent',
            name='link',
            field=models.CharField(default=None, max_length=20, verbose_name='Ссылка'),
        ),
    ]
